name: soniox_transcriptor
description: 'A new Flutter project.'
publish_to: 'none'
version: 0.1.0+1

environment:
  sdk: ^3.11.5

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  flutter_animate: ^4.5.2
  gap: ^3.0.1
  get_it: ^9.2.1
  shared_preferences: ^2.5.5
  flutter_riverpod: ^2.6.1
  riverpod: ^2.6.1
  vit_soniox: ^1.0.0
  record: ^6.2.1
  web_socket_channel: ^3.0.3
  vit_dart_extensions: ^4.2.0
  sqlite3: ^3.3.1
  path_provider: ^2.1.0
  path: ^1.8.3
  liquid_glass_widgets: ^0.12.8

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0

flutter:
  uses-material-design: true
